# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error_default.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import QTimer, QMetaObject, Qt
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPainter
global x
x = 0
y = 0
autoClose = 0
import sys
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(525, 199)
        Dialog.setStyleSheet("font: 8pt \"Space Grotesk\"; background-color:#ffffff;")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 151, 151))
        self.label.setObjectName("label")
        # self.label_2 = QtWidgets.QLabel(Dialog)
        # self.label_2.setGeometry(QtCore.QRect(170, 10, 341, 61))
        # self.label_2.setStyleSheet("")
        # self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(170, 10, 341, 151))
        self.textBrowser.setStyleSheet("background-color: rgb(0, 0, 0);\n"
        "font: 14pt \"Space Mono\";\n"
        "background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(16, 170, 491, 20))
        self.label_3.setObjectName("label_3")

#####ANIMATE###########
        self._update_timer = QtCore.QTimer()
        self._update_timer.start(250)
        self._update_timer.timeout.connect(self.restartAnimation)
        self.update_error(sys.argv[1])
#######################


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def update_error(self,data):
        # _translate = QtCore.QCoreApplication.translate
        self.textBrowser.setText(str(data))
    
    def restartAnimation(self):
        global x,y, autoClose
        _translate = QtCore.QCoreApplication.translate
        if autoClose == 100:
            sys.exit()
        if x == 0:
            self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600; color:#058a00;\">/ ! \\</span></p></body></html>"))
            x = 1
            y = 1
        else:
            self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600; color:#00ff00;\">/ ! \\</span></p></body></html>"))
            x = 0
        if y == 1:
            # self.update_error(sys.argv[1])
            y = 0
        autoClose +=1 
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "OPD System Notification Handler"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600; color:#09b304;\">/ ! \\</span></p></body></html>"))
        # self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:22pt; color:#058a00;\">Notification !</span><span style=\" font-size:22pt; color:#ff0004;\"><br/></span><span style=\" font-size:10pt; color:#000000;\">Plainsboro SD - Notification Handler</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Space Mono\'; background-color:white;  font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Error Trace :</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Exception Example</p></body></html>"))
        if "not a valid" in sys.argv[1]:
            self.update_error("User not found in the database.")
        else :
            self.update_error(sys.argv[1])
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">v.0.0.2</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    Dialog.setWindowFlags(Dialog.windowFlags() | QtCore.Qt.WindowStaysOnTopHint)  # Set the dialog to stay on top
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
