# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import os
import subprocess


def error(error):
    subprocess.Popen(["pythonw", "notifications/error.py", error])


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(511, 320)  # Increased height to accommodate new button
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                             "color: rgb(0, 0, 0);\n"
                             "font: 25 8pt \"Space Grotesk Medium\";\n"
                             "\n"
                             "")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 231, 221))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setPixmap(QtGui.QPixmap("../resources/Images/clothing.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(250, 10, 251, 31))
        self.label_2.setStyleSheet("/* QLabel Style */\n"
                                   "QLabel {\n"
                                   "    color: #000; /* Black */\n"
                                   "    font-size: 18px;\n"
                                   "    font-weight: bold;\n"
                                   "}\n"
                                   "\n"
                                   "")
        self.label_2.setObjectName("label_2")

        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 60, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Space Grotesk Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(3)
        font.setStrikeOut(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(self.buttonStyle())
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 120, 251, 51))
        self.pushButton_3.setStyleSheet(self.buttonStyle())
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 180, 251, 51))
        self.pushButton_4.setStyleSheet(self.buttonStyle())
        self.pushButton_4.setObjectName("pushButton_4")

        # Add new Admin button
        self.pushButton_admin = QtWidgets.QPushButton(Dialog)
        self.pushButton_admin.setGeometry(QtCore.QRect(250, 240, 251, 51))  # Position for the Admin button
        self.pushButton_admin.setStyleSheet(self.buttonStyle())
        self.pushButton_admin.setObjectName("pushButton_admin")

        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 290, 491, 20))
        self.label_3.setObjectName("label_3")

        # Connect buttons to their functions
        self.pushButton_3.clicked.connect(self.openUser)
        self.pushButton_2.clicked.connect(self.openDoctor)
        self.pushButton_4.clicked.connect(self.openPharmacy)
        self.pushButton_admin.clicked.connect(self.openAdmin)  # Connect Admin button to function

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def buttonStyle(self):
        return """/* QPushButton Style */
QPushButton {
    background-color: #000; /* Black */
    border: none;
    color: #FFF; /* White */
    padding: 12px 24px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    transition-duration: 0.4s;
    cursor: pointer;
    border-radius: 8px;
}
QPushButton:hover {
    background-color: #333; /* Darker Gray */
}
QPushButton:pressed {
    background-color: #666; /* Even Darker Gray */
    box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
}
"""

    def error(error):
        subprocess.Popen(["pythonw", "notifications/error.py", error], creationflags=subprocess.CREATE_NO_WINDOW)

    def openUser(self):
        try:
            subprocess.Popen(["pythonw", "login-patient.py"], creationflags=subprocess.CREATE_NO_WINDOW)
        except Exception as e:
            error(str(e))

    def openDoctor(self):
        try:
            subprocess.Popen(["pythonw", "login-doctor.py"], creationflags=subprocess.CREATE_NO_WINDOW)
        except Exception as e:
            error(str(e))

    def openPharmacy(self):
        try:
            subprocess.Popen(["pythonw", "pharmacy.py"], creationflags=subprocess.CREATE_NO_WINDOW)
        except Exception as e:
            error(str(e))

    def openAdmin(self):
        try:
            subprocess.Popen(["pythonw", "login-admin.py"], creationflags=subprocess.CREATE_NO_WINDOW)
        except Exception as e:
            error(str(e))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Princeton Plainsboro Software Department - OPD Management System"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Select Login Environment :</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Dialog", "Doctor ⚕"))
        self.pushButton_3.setText(_translate("Dialog", "Patient 🏥"))
        self.pushButton_4.setText(_translate("Dialog", "Pharmacy 💊"))
        self.pushButton_admin.setText(_translate("Dialog", "Admin 🔑"))  # Add text for Admin button
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Hospital Management System | v 0.0.1 Dev</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

